//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.312
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Amnesty_Hypercube.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Amnesty_Hypercube.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap Back {
            get {
                object obj = ResourceManager.GetObject("Back", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BackDown {
            get {
                object obj = ResourceManager.GetObject("BackDown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BackOver {
            get {
                object obj = ResourceManager.GetObject("BackOver", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Blank {
            get {
                object obj = ResourceManager.GetObject("Blank", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///&lt;head&gt;
        ///&lt;meta http-equiv=&quot;refresh&quot; content=&quot;0; URL=^url&quot;&gt;
        ///&lt;/head&gt;
        ///
        ///&lt;body&gt;
        ///&lt;/body&gt;
        ///&lt;/html&gt;
        ///.
        /// </summary>
        internal static string Browser {
            get {
                return ResourceManager.GetString("Browser", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap BrowserClose {
            get {
                object obj = ResourceManager.GetObject("BrowserClose", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BrowserResize {
            get {
                object obj = ResourceManager.GetObject("BrowserResize", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream Click {
            get {
                return ResourceManager.GetStream("Click", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Close {
            get {
                object obj = ResourceManager.GetObject("Close", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CloseDown {
            get {
                object obj = ResourceManager.GetObject("CloseDown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CloseOver {
            get {
                object obj = ResourceManager.GetObject("CloseOver", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream Create {
            get {
                return ResourceManager.GetStream("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        internal static string CreditsDone {
            get {
                return ResourceManager.GetString("CreditsDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More Credits....
        /// </summary>
        internal static string CreditsMore {
            get {
                return ResourceManager.GetString("CreditsMore", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Cube {
            get {
                object obj = ResourceManager.GetObject("Cube", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CubeDown {
            get {
                object obj = ResourceManager.GetObject("CubeDown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cube Gallery.
        /// </summary>
        internal static string CubeGallery {
            get {
                return ResourceManager.GetString("CubeGallery", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap CubeOver {
            get {
                object obj = ResourceManager.GetObject("CubeOver", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cube.
        /// </summary>
        internal static string CubeTitle {
            get {
                return ResourceManager.GetString("CubeTitle", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Down {
            get {
                object obj = ResourceManager.GetObject("Down", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DownDown {
            get {
                object obj = ResourceManager.GetObject("DownDown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DownOver {
            get {
                object obj = ResourceManager.GetObject("DownOver", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream Enter {
            get {
                return ResourceManager.GetStream("Enter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to Download Page.
        /// </summary>
        internal static string ExpiredDownload {
            get {
                return ResourceManager.GetString("ExpiredDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This alpha version of Amnesty Hypercube has expired.  Do you want to go to the download page now?.
        /// </summary>
        internal static string ExpiredMessage {
            get {
                return ResourceManager.GetString("ExpiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string ExpiredQuit {
            get {
                return ResourceManager.GetString("ExpiredQuit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alpha Expiration.
        /// </summary>
        internal static string ExpiredTitle {
            get {
                return ResourceManager.GetString("ExpiredTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Featured.
        /// </summary>
        internal static string FeaturedProvider {
            get {
                return ResourceManager.GetString("FeaturedProvider", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Forward {
            get {
                object obj = ResourceManager.GetObject("Forward", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ForwardDown {
            get {
                object obj = ResourceManager.GetObject("ForwardDown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ForwardOver {
            get {
                object obj = ResourceManager.GetObject("ForwardOver", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to body {
        ///	margin: 0px;
        ///	background-image: url(front.png);
        ///	width: 320px;
        ///	height: 240px;
        ///}
        ///
        ///#gadget {
        ///}
        ///.
        /// </summary>
        internal static string gcss {
            get {
                return ResourceManager.GetString("gcss", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap gfront {
            get {
                object obj = ResourceManager.GetObject("gfront", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///&lt;head&gt;
        ///	&lt;meta http-equiv=&quot;content-type&quot; content=&quot;text/html; charset=utf-8&quot;&gt;
        ///	&lt;meta name=&quot;GENERATOR&quot; content=&quot;Amnesty Generator 0.5b&quot;&gt;
        ///	&lt;style type=&quot;text/css&quot;&gt;
        ///		@import &quot;generator.css&quot;;
        ///	&lt;/style&gt;
        ///	&lt;script type=&apos;text/javascript&apos; src=&apos;generator.js&apos; charset=&quot;utf-8&quot;&gt;&lt;/script&gt;
        ///&lt;/head&gt;
        ///
        ///&lt;body onfocus=&apos;generator_setup();&apos;&gt;
        ///	&lt;div id=&quot;gadget&quot; onmouseover=&apos;generator_track();&apos;&gt;
        ///	&lt;/div&gt;
        ///&lt;/body&gt;
        ///&lt;/html&gt;
        ///.
        /// </summary>
        internal static string ghtm {
            get {
                return ResourceManager.GetString("ghtm", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap gicon {
            get {
                object obj = ResourceManager.GetObject("gicon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // Copyright 2006-2007 Mesa Dynamics, LLC
        ///
        ///var GeneratorPlugin = 0;
        ///
        ///function generator_setup()
        ///{
        ///	if(GeneratorPlugin)
        ///		GeneratorPlugin.registerWidget(&quot;com.mesadynamics.widget.Generator&quot;, &quot;0000-0000-0000-0000&quot;);
        ///
        ///	if(window.widget) {
        ///		widget.onshow = generator_onshow;
        ///		widget.onhide = generator_onhide;
        ///
        ///		window.open = generator_open;
        ///	}
        ///}
        ///
        ///function generator_dismiss()
        ///{
        ///	if(GeneratorPlugin)
        ///		widget.openURL(&apos;&apos;);
        ///}
        ///
        ///function generator_track()
        ///{
        ///	if(GeneratorPlugin)
        ///		GeneratorPl [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string gjs {
            get {
                return ResourceManager.GetString("gjs", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap glogo {
            get {
                object obj = ResourceManager.GetObject("glogo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Gradient {
            get {
                object obj = ResourceManager.GetObject("Gradient", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;gadget&gt;
        ///  &lt;name&gt;Generator&lt;/name&gt;
        ///  &lt;namespace&gt;com.mesadynamics.widget.Generator&lt;/namespace&gt;
        ///  &lt;version&gt;1.0.0.0&lt;/version&gt;
        ///  &lt;author&gt;
        ///    &lt;info url=&quot;www.mesadynamics.com&quot; /&gt;
        ///    &lt;logo src=&quot;logo.png&quot; /&gt;
        ///  &lt;/author&gt;
        ///  &lt;copyright&gt;Mesa Dynamics&lt;/copyright&gt;
        ///  &lt;description&gt;Powered by Amnesty™ Generator.&lt;/description&gt;
        ///  &lt;icons&gt;
        ///    &lt;icon width=&quot;64&quot; height=&quot;64&quot; src=&quot;icon.png&quot; /&gt;
        ///  &lt;/icons&gt;
        ///  &lt;hosts&gt;
        ///    &lt;host name=&quot;sidebar&quot;&gt;
        ///      &lt;base type=&quot;HTML&quot; apiVersion=&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string gxml {
            get {
                return ResourceManager.GetString("gxml", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Help {
            get {
                object obj = ResourceManager.GetObject("Help", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap HelpDown {
            get {
                object obj = ResourceManager.GetObject("HelpDown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap HelpOver {
            get {
                object obj = ResourceManager.GetObject("HelpOver", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hypercube.
        /// </summary>
        internal static string Hypercube {
            get {
                return ResourceManager.GetString("Hypercube", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info Center.
        /// </summary>
        internal static string InfoCenter {
            get {
                return ResourceManager.GetString("InfoCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iPhone Application.
        /// </summary>
        internal static string IPhoneApp {
            get {
                return ResourceManager.GetString("IPhoneApp", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap LargeCube {
            get {
                object obj = ResourceManager.GetObject("LargeCube", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LargeGear {
            get {
                object obj = ResourceManager.GetObject("LargeGear", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LargeWorld {
            get {
                object obj = ResourceManager.GetObject("LargeWorld", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Library {
            get {
                object obj = ResourceManager.GetObject("Library", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LibraryDown {
            get {
                object obj = ResourceManager.GetObject("LibraryDown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LibraryOver {
            get {
                object obj = ResourceManager.GetObject("LibraryOver", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Logo {
            get {
                object obj = ResourceManager.GetObject("Logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Options {
            get {
                object obj = ResourceManager.GetObject("Options", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        internal static string OtherProvider {
            get {
                return ResourceManager.GetString("OtherProvider", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap PreAll {
            get {
                object obj = ResourceManager.GetObject("PreAll", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PreAllDown {
            get {
                object obj = ResourceManager.GetObject("PreAllDown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PreAllOver {
            get {
                object obj = ResourceManager.GetObject("PreAllOver", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PreDirectory {
            get {
                object obj = ResourceManager.GetObject("PreDirectory", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PreDirectoryDown {
            get {
                object obj = ResourceManager.GetObject("PreDirectoryDown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PreDirectoryOver {
            get {
                object obj = ResourceManager.GetObject("PreDirectoryOver", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PreGames {
            get {
                object obj = ResourceManager.GetObject("PreGames", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PreGamesDown {
            get {
                object obj = ResourceManager.GetObject("PreGamesDown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PreGamesOver {
            get {
                object obj = ResourceManager.GetObject("PreGamesOver", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PreMusic {
            get {
                object obj = ResourceManager.GetObject("PreMusic", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PreMusicDown {
            get {
                object obj = ResourceManager.GetObject("PreMusicDown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PreMusicOver {
            get {
                object obj = ResourceManager.GetObject("PreMusicOver", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PreOther {
            get {
                object obj = ResourceManager.GetObject("PreOther", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PreOtherDown {
            get {
                object obj = ResourceManager.GetObject("PreOtherDown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PreOtherOver {
            get {
                object obj = ResourceManager.GetObject("PreOtherOver", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PrePhotos {
            get {
                object obj = ResourceManager.GetObject("PrePhotos", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PrePhotosDown {
            get {
                object obj = ResourceManager.GetObject("PrePhotosDown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PrePhotosOver {
            get {
                object obj = ResourceManager.GetObject("PrePhotosOver", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PreVideo {
            get {
                object obj = ResourceManager.GetObject("PreVideo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PreVideoDown {
            get {
                object obj = ResourceManager.GetObject("PreVideoDown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PreVideoOver {
            get {
                object obj = ResourceManager.GetObject("PreVideoOver", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provider Gallery.
        /// </summary>
        internal static string ProviderGallery {
            get {
                return ResourceManager.GetString("ProviderGallery", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Providers {
            get {
                object obj = ResourceManager.GetObject("Providers", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ProvidersDown {
            get {
                object obj = ResourceManager.GetObject("ProvidersDown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ProvidersOver {
            get {
                object obj = ResourceManager.GetObject("ProvidersOver", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove from Desktop.
        /// </summary>
        internal static string RemoveDesktop {
            get {
                return ResourceManager.GetString("RemoveDesktop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove from Cube.
        /// </summary>
        internal static string RemoveHypercube {
            get {
                return ResourceManager.GetString("RemoveHypercube", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A gadget named &quot;{0}&quot; is already installed in your Gallery.  Do you want to replace it?.
        /// </summary>
        internal static string SidebarConfirm {
            get {
                return ResourceManager.GetString("SidebarConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to install the gadget &quot;{0}&quot; into your Windows Sidebar Gallery?.
        /// </summary>
        internal static string SidebarInstall {
            get {
                return ResourceManager.GetString("SidebarInstall", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap SmallGear {
            get {
                object obj = ResourceManager.GetObject("SmallGear", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SplashHypercube {
            get {
                object obj = ResourceManager.GetObject("SplashHypercube", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SplashHypercube2 {
            get {
                object obj = ResourceManager.GetObject("SplashHypercube2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream Switch {
            get {
                return ResourceManager.GetStream("Switch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        internal static string TipPresetAll {
            get {
                return ResourceManager.GetString("TipPresetAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fun and Games.
        /// </summary>
        internal static string TipPresetGames {
            get {
                return ResourceManager.GetString("TipPresetGames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iPhone Applications.
        /// </summary>
        internal static string TipPresetIPhone {
            get {
                return ResourceManager.GetString("TipPresetIPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Widget Directories.
        /// </summary>
        internal static string TipPresetLibraries {
            get {
                return ResourceManager.GetString("TipPresetLibraries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Music Players.
        /// </summary>
        internal static string TipPresetMusic {
            get {
                return ResourceManager.GetString("TipPresetMusic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Widgets.
        /// </summary>
        internal static string TipPresetOther {
            get {
                return ResourceManager.GetString("TipPresetOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo Slideshows.
        /// </summary>
        internal static string TipPresetPhotos {
            get {
                return ResourceManager.GetString("TipPresetPhotos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Embeddable Video.
        /// </summary>
        internal static string TipPresetVideo {
            get {
                return ResourceManager.GetString("TipPresetVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown Widget.
        /// </summary>
        internal static string UnknownWidget {
            get {
                return ResourceManager.GetString("UnknownWidget", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Up {
            get {
                object obj = ResourceManager.GetObject("Up", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for Updates....
        /// </summary>
        internal static string UpdateCheck {
            get {
                return ResourceManager.GetString("UpdateCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to Download Page.
        /// </summary>
        internal static string UpdateDownload {
            get {
                return ResourceManager.GetString("UpdateDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your version of Amnesty Hypercube is up to date.  There are no updates available at this time..
        /// </summary>
        internal static string UpdateNo {
            get {
                return ResourceManager.GetString("UpdateNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A new version of Amnesty Hypercube is available.  Do you want to go to the download page now?.
        /// </summary>
        internal static string UpdateYes {
            get {
                return ResourceManager.GetString("UpdateYes", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap UpDown {
            get {
                object obj = ResourceManager.GetObject("UpDown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap UpOver {
            get {
                object obj = ResourceManager.GetObject("UpOver", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream Welcome {
            get {
                return ResourceManager.GetStream("Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to Amnesty Hypercube.
        /// </summary>
        internal static string WelcomeTitle {
            get {
                return ResourceManager.GetString("WelcomeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///&lt;head&gt;
        ///	&lt;meta http-equiv=&quot;content-type&quot; content=&quot;text/html; charset=utf-8&quot;&gt;
        ///	&lt;style type=&quot;text/css&quot;&gt;
        ///&lt;!--
        ///body {
        ///	margin: 0px;
        ///	background: #FEFFFE;
        ///}
        ///#widget {
        ///	background-color: none;
        ///}
        ///--&gt;
        ///	&lt;/style&gt;
        ///	&lt;script type=&quot;text/javascript&quot;&gt;
        ///&lt;!--
        ///	var widgetString = &quot;&quot;;
        ///	
        ///	function HCDisableSelection() {
        ///		target = document.getElementById(&quot;widget&quot;);
        ///		
        ///		if(typeof target.onselectstart != &quot;undefined&quot;)
        ///			target.onselectstart = function() { return false };
        ///		else if(typeof target.style. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Widget {
            get {
                return ResourceManager.GetString("Widget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Widget Gallery.
        /// </summary>
        internal static string WidgetGallery {
            get {
                return ResourceManager.GetString("WidgetGallery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Widget.
        /// </summary>
        internal static string WidgetTitle {
            get {
                return ResourceManager.GetString("WidgetTitle", resourceCulture);
            }
        }
    }
}
