//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1434
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Amnesty_Hypercube.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Amnesty_Hypercube.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap _Bebo {
            get {
                object obj = ResourceManager.GetObject("_Bebo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _Facebook {
            get {
                object obj = ResourceManager.GetObject("_Facebook", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _Friendster {
            get {
                object obj = ResourceManager.GetObject("_Friendster", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _Hi5 {
            get {
                object obj = ResourceManager.GetObject("_Hi5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _MySpace {
            get {
                object obj = ResourceManager.GetObject("_MySpace", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _Orkut {
            get {
                object obj = ResourceManager.GetObject("_Orkut", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _Sidebar {
            get {
                object obj = ResourceManager.GetObject("_Sidebar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _Widgetbox {
            get {
                object obj = ResourceManager.GetObject("_Widgetbox", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _Yahoo {
            get {
                object obj = ResourceManager.GetObject("_Yahoo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Action {
            get {
                object obj = ResourceManager.GetObject("Action", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Action_Pressed {
            get {
                object obj = ResourceManager.GetObject("Action_Pressed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Add {
            get {
                object obj = ResourceManager.GetObject("Add", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Add_Pressed {
            get {
                object obj = ResourceManager.GetObject("Add_Pressed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Back {
            get {
                object obj = ResourceManager.GetObject("Back", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BackDown {
            get {
                object obj = ResourceManager.GetObject("BackDown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BlackBar {
            get {
                object obj = ResourceManager.GetObject("BlackBar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Bottom {
            get {
                object obj = ResourceManager.GetObject("Bottom", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BottomBar {
            get {
                object obj = ResourceManager.GetObject("BottomBar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the collection titled &quot;{0}&quot;?.
        /// </summary>
        internal static string ConfirmDeleteProvider {
            get {
                return ResourceManager.GetString("ConfirmDeleteProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Delete.
        /// </summary>
        internal static string ConfirmDeleteTitle {
            get {
                return ResourceManager.GetString("ConfirmDeleteTitle", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap DBSourceSplitViewThumb {
            get {
                object obj = ResourceManager.GetObject("DBSourceSplitViewThumb", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Forward {
            get {
                object obj = ResourceManager.GetObject("Forward", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ForwardDown {
            get {
                object obj = ResourceManager.GetObject("ForwardDown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Home {
            get {
                object obj = ResourceManager.GetObject("Home", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Home_Pressed {
            get {
                object obj = ResourceManager.GetObject("Home_Pressed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap HomeDown {
            get {
                object obj = ResourceManager.GetObject("HomeDown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Icon Icon {
            get {
                object obj = ResourceManager.GetObject("Icon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap IconCloseAll {
            get {
                object obj = ResourceManager.GetObject("IconCloseAll", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap IconCube {
            get {
                object obj = ResourceManager.GetObject("IconCube", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap IconDisabled {
            get {
                object obj = ResourceManager.GetObject("IconDisabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap IconExplore {
            get {
                object obj = ResourceManager.GetObject("IconExplore", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap IconFavorite {
            get {
                object obj = ResourceManager.GetObject("IconFavorite", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap IconFull {
            get {
                object obj = ResourceManager.GetObject("IconFull", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap IconHideAll {
            get {
                object obj = ResourceManager.GetObject("IconHideAll", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap IconInfo {
            get {
                object obj = ResourceManager.GetObject("IconInfo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap IconOpen {
            get {
                object obj = ResourceManager.GetObject("IconOpen", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap IconRunning {
            get {
                object obj = ResourceManager.GetObject("IconRunning", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap IconShowAll {
            get {
                object obj = ResourceManager.GetObject("IconShowAll", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap IconSleeping {
            get {
                object obj = ResourceManager.GetObject("IconSleeping", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap IconStar {
            get {
                object obj = ResourceManager.GetObject("IconStar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap IconWeb {
            get {
                object obj = ResourceManager.GetObject("IconWeb", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap IconWebLoading {
            get {
                object obj = ResourceManager.GetObject("IconWebLoading", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap IconWorld {
            get {
                object obj = ResourceManager.GetObject("IconWorld", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LCD {
            get {
                object obj = ResourceManager.GetObject("LCD", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have any widgets in your library.  Do you want to load a default set of widgets?.
        /// </summary>
        internal static string LoadDefault {
            get {
                return ResourceManager.GetString("LoadDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Widget Library Empty.
        /// </summary>
        internal static string LoadDefaultTitle {
            get {
                return ResourceManager.GetString("LoadDefaultTitle", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap NoImage {
            get {
                object obj = ResourceManager.GetObject("NoImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Reload {
            get {
                object obj = ResourceManager.GetObject("Reload", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ReloadDown {
            get {
                object obj = ResourceManager.GetObject("ReloadDown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SmallGear {
            get {
                object obj = ResourceManager.GetObject("SmallGear", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Stop {
            get {
                object obj = ResourceManager.GetObject("Stop", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap StopDown {
            get {
                object obj = ResourceManager.GetObject("StopDown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close all running widgets.
        /// </summary>
        internal static string TipCloseAll {
            get {
                return ResourceManager.GetString("TipCloseAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explore selected publisher web site.
        /// </summary>
        internal static string TipExplore {
            get {
                return ResourceManager.GetString("TipExplore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle fullscreen mode.
        /// </summary>
        internal static string TipFull {
            get {
                return ResourceManager.GetString("TipFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide all running widgets.
        /// </summary>
        internal static string TipHideAll {
            get {
                return ResourceManager.GetString("TipHideAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle widget info panel.
        /// </summary>
        internal static string TipInfo {
            get {
                return ResourceManager.GetString("TipInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launch selected widget on desktop.
        /// </summary>
        internal static string TipLaunch {
            get {
                return ResourceManager.GetString("TipLaunch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show all running widgets.
        /// </summary>
        internal static string TipShowAll {
            get {
                return ResourceManager.GetString("TipShowAll", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Top {
            get {
                object obj = ResourceManager.GetObject("Top", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
